// src/avatars.js
// Profile avatars (v2.1.2). One list for the picker AND the server, which
// validates saves against it (lib/avatars.js), the same way src/version.js is
// shared. Files live in public/avatars/.
//
// adult: true means 21+ only: smoke, joints, cannabis leaves (even on a beanie,
// bandana or sunglasses), rolling trays, neon spotted mushrooms. The vibe tab is
// open to 13 and up, so those stay behind the same gate as Talk the Plant.

export const AVATAR_PATH = "/avatars/";

export const AVATARS = [
  { id: "moai-headphones", file: "moai-headphones.webp", label: "stonehead in headphones", adult: false },
  { id: "moai-shades", file: "moai-shades.webp", label: "stonehead in shades", adult: false },
  { id: "moai-round-glasses", file: "moai-round-glasses.webp", label: "stonehead in round glasses", adult: false },
  { id: "moai-visor", file: "moai-visor.webp", label: "stonehead in a visor", adult: false },
  { id: "alien-headphones", file: "alien-headphones.webp", label: "alien in headphones", adult: false },
  { id: "raccoon-bucket-hat", file: "raccoon-bucket-hat.webp", label: "raccoon in a bucket hat", adult: false },
  { id: "moai-ferns", file: "moai-ferns.webp", label: "stonehead in the ferns", adult: false },
  { id: "astronaut-galaxy", file: "astronaut-galaxy.webp", label: "astronaut with a galaxy visor", adult: false },
  { id: "wolf-moon", file: "wolf-moon.webp", label: "wolf under the moon", adult: false },
  { id: "ghost-forest", file: "ghost-forest.webp", label: "friendly ghost", adult: false },
  { id: "owl-moon", file: "owl-moon.webp", label: "owl under the moon", adult: false },
  { id: "hippie-van", file: "hippie-van.webp", label: "hippie van", adult: false },
  { id: "ufo-forest", file: "ufo-forest.webp", label: "ufo over the forest", adult: false },
  { id: "rainbow-slime", file: "rainbow-slime.webp", label: "rainbow slime", adult: false },
  { id: "moai-sleeping", file: "moai-sleeping.webp", label: "sleeping stonehead", adult: false },
  { id: "moai-joint", file: "moai-joint.webp", label: "stonehead with a joint", adult: true },
  { id: "moai-mushroom-purple", file: "moai-mushroom-purple.webp", label: "purple mushroom stonehead", adult: true },
  { id: "moai-mossy", file: "moai-mossy.webp", label: "mossy stonehead", adult: true },
  { id: "moai-hoodie", file: "moai-hoodie.webp", label: "stonehead in a hoodie", adult: true },
  { id: "moai-mushroom-tongue", file: "moai-mushroom-tongue.webp", label: "tongue-out mushroom stonehead", adult: true },
  { id: "moai-leaf", file: "moai-leaf.webp", label: "stonehead with a leaf", adult: true },
  { id: "moai-mushroom-sparkle", file: "moai-mushroom-sparkle.webp", label: "sparkly mushroom stonehead", adult: true },
  { id: "moai-beanie", file: "moai-beanie.webp", label: "stonehead in a beanie", adult: true },
  { id: "moai-mushroom-green", file: "moai-mushroom-green.webp", label: "green mushroom stonehead", adult: true },
  { id: "moai-mushroom-sprouts", file: "moai-mushroom-sprouts.webp", label: "stonehead growing mushrooms", adult: true },
  { id: "moai-mushroom-pink", file: "moai-mushroom-pink.webp", label: "pink swirl mushroom stonehead", adult: true },
  { id: "moai-goggles", file: "moai-goggles.webp", label: "stonehead in goggles", adult: true },
  { id: "moai-mossy-wisps", file: "moai-mossy-wisps.webp", label: "mossy stonehead with wisps", adult: true },
  { id: "moai-leaf-shades", file: "moai-leaf-shades.webp", label: "stonehead in leaf shades", adult: true },
  { id: "moai-mushroom-drip", file: "moai-mushroom-drip.webp", label: "dripping mushroom stonehead", adult: true },
  { id: "moai-leaves", file: "moai-leaves.webp", label: "stonehead in the leaves", adult: true },
  { id: "moai-smoke", file: "moai-smoke.webp", label: "stonehead smoking", adult: true },
  { id: "alien", file: "alien.webp", label: "alien", adult: true },
  { id: "mushroom-buddy", file: "mushroom-buddy.webp", label: "mushroom buddy", adult: true },
  { id: "black-cat", file: "black-cat.webp", label: "black cat", adult: true },
  { id: "sun", file: "sun.webp", label: "sun in shades", adult: true },
  { id: "panda", file: "panda.webp", label: "panda", adult: true },
  { id: "leaf-buddy", file: "leaf-buddy.webp", label: "leaf buddy", adult: true },
  { id: "melting-mushroom", file: "melting-mushroom.webp", label: "melting mushroom", adult: true },
  { id: "raccoon", file: "raccoon.webp", label: "raccoon", adult: true },
  { id: "astronaut", file: "astronaut.webp", label: "astronaut", adult: true },
  { id: "wolf", file: "wolf.webp", label: "wolf", adult: true },
  { id: "jar-buddy", file: "jar-buddy.webp", label: "jar buddy", adult: true },
  { id: "ghost", file: "ghost.webp", label: "ghost", adult: true },
  { id: "dreads", file: "dreads.webp", label: "buddy with dreads", adult: true },
  { id: "ufo", file: "ufo.webp", label: "ufo", adult: true },
  { id: "stash-tin", file: "stash-tin.webp", label: "stash tin", adult: true },
  { id: "owl", file: "owl.webp", label: "owl", adult: true },
  { id: "mushroom-patch", file: "mushroom-patch.webp", label: "mushroom patch", adult: true },
  { id: "bandana-dog", file: "bandana-dog.webp", label: "dog in a bandana", adult: true },
  { id: "moai-green-smoke", file: "moai-green-smoke.webp", label: "stonehead with green smoke", adult: true },
  { id: "mushroom-buddy-leaves", file: "mushroom-buddy-leaves.webp", label: "mushroom buddy in the leaves", adult: true },
  { id: "black-cat-beanie", file: "black-cat-beanie.webp", label: "black cat in a beanie", adult: true },
  { id: "sun-swirls", file: "sun-swirls.webp", label: "sun with swirls", adult: true },
  { id: "panda-beanie", file: "panda-beanie.webp", label: "panda in a beanie", adult: true },
  { id: "dreads-backpacker", file: "dreads-backpacker.webp", label: "backpacker with dreads", adult: true },
  { id: "rolling-tray", file: "rolling-tray.webp", label: "rolling tray", adult: true },
  { id: "mushroom-grove", file: "mushroom-grove.webp", label: "mushroom grove", adult: true },
  { id: "golden-dog", file: "golden-dog.webp", label: "golden dog", adult: true },
];
